spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/metadata_db
    username: metadata_user
    password: metadata_pass
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

management:
  tracing:
    sampling:
      probability: 1.0

logging:
  level:
    com.dataplatform.ms: DEBUG
