
# -----------------------
# S3A (LocalStack)
# -----------------------
spark.hadoop.fs.s3a.endpoint=http://localstack:4566
spark.hadoop.fs.s3a.access.key=test
spark.hadoop.fs.s3a.secret.key=test
spark.hadoop.fs.s3a.path.style.access=true
spark.hadoop.fs.s3a.connection.ssl.enabled=false
spark.hadoop.fs.s3a.impl=org.apache.hadoop.fs.s3a.S3AFileSystem

# -----------------------
# Stability (recommended)
# -----------------------
spark.sql.shuffle.partitions=4
spark.default.parallelism=4
